springdoc:
  swagger-ui:
    disable-swagger-default-url: true

spring:
  data:
    mongodb:
      uri: mongodb://mirante_user:123456@localhost:27017/mirante_db
      auto-index-creation: true

  servlet:
    multipart:
      enabled: true           # Whether to enable support of multipart uploads.
      max-file-size: 1MB      # Max file size
      max-request-size: 10MB  # Max request size.

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: info